# create your drupal and postgres config here, based off the last assignment
services:
  custom-drupal:
    image: drupal:9.3.13
    build: .
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
      - drupal-data:/var/lib/postgresql/data
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_PASSWORD=mypasswd

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:
